language: php

matrix:
  include:
    - php: 5.3
      dist: precise
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.1

before_script:
  - composer install --dev
script:
  - ./vendor/bin/phpunit
  - ./vendor/bin/phpcs --extensions=php --report=summary --standard=PSR2 ./src ./tests
